### ISSUE TITLE
ReferenceError: 'slice_and_union' is not defined

### ISSUE THREAD

**Issue by jackellenberger** [bluelightning32/dactyl-openjscad#1]
<img src="https://emoji.slack-edge.com/T5BMY90QG/blob-wave/d5ef89d069437c2b.gif" alt="blob-wave" title="blob-wave" aria-label=":blob-wave:" height="21" align="top"> I'm trying to get started using this project, but it seems like something may have been lost in translation, or (more likely) I'm doing something wrong.

Having loaded `main`, `get_plane_normal`, `gl_vec3`, `point_line_distance`, and `quickhull3d` into jscad (windows store version in my case), I can't switch to the `extended bottom right` part because the method [slice_and_union](https://github.com/bluelightning32/dactyl-openjscad/blob/8e020fbc5efce9278ddb5cba1c65b1699a18f2f8/main.jscad#L1886) isn't defined.

Is this method defined in another version perhaps? or are the extended versions just not operable and I should ignore them? Either way, thank you for your work on this project, it is amazing how much faster jscad is than openscad!

**Comment by bluelightning32** [comment]
Sorry, I just now saw this. I don't know why I didn't get an email. When you filed it.

Unfortunately the extended bottom does not work. I had some local commits that produced something, but they were unprintable due to a bug in openjscad: https://github.com/jscad/OpenJSCAD.org/issues/451

**Comment by jackellenberger** [comment]
Got it, no problem! thanks for the clarification!
